version: "3.9"

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis.conf
    command: ["redis-server", "/usr/local/etc/redis.conf"]

volumes:
  redis_data:
    driver: local
